import api from "../config/axiosInstance";
import { API_CONFIG } from "../config/apiConfig";
import { getUsernameFromToken } from "../../helper";

const HISTORY_API = api.create({
  baseURL: API_CONFIG.AI_BASE,
  timeout: 15000,
  withCredentials: true,
});
const inFlightRequests = new Map();

const getUserPhoneHeader = () => {
  const userPhone = getUsernameFromToken();
  return {
    "X-User-Phone": userPhone || "",
  };
};

const runDeduped = (key, requestFactory) => {
  if (inFlightRequests.has(key)) {
    return inFlightRequests.get(key);
  }

  const promise = requestFactory().finally(() => {
    inFlightRequests.delete(key);
  });

  inFlightRequests.set(key, promise);
  return promise;
};

export const fetchKisanMitraHistory = async ({ page = 0, size = 20 } = {}) => {
  const userPhone = getUsernameFromToken() || "guest";
  const key = `chat:${userPhone}:${page}:${size}`;

  return runDeduped(key, async () => {
    const response = await HISTORY_API.get("/chat/history", {
      params: { page, size },
      headers: getUserPhoneHeader(),
      withCredentials: true,
    });
    return response.data;
  });
};

export const fetchCropAdvisoryHistory = async ({ page = 0, size = 20 } = {}) => {
  const userPhone = getUsernameFromToken() || "guest";
  const key = `crop:${userPhone}:${page}:${size}`;

  return runDeduped(key, async () => {
    const response = await HISTORY_API.get("/crop/history", {
      params: { page, size },
      headers: getUserPhoneHeader(),
      withCredentials: true,
    });
    return response.data;
  });
};

export const deleteKisanMitraHistory = async ({ conversationId } = {}) => {
  const response = await HISTORY_API.delete("/chat/history", {
    params: conversationId ? { conversationId } : undefined,
    headers: getUserPhoneHeader(),
    withCredentials: true,
  });
  return response.data;
};

export const deleteConversationById = async (conversationId) => {
  const response = await HISTORY_API.delete(`/chat/conversations/${conversationId}`, {
    headers: getUserPhoneHeader(),
    withCredentials: true,
  });
  return response.data;
};

export const deleteAllAiHistory = async () => {
  const response = await HISTORY_API.delete("/history/all", {
    headers: getUserPhoneHeader(),
    withCredentials: true,
  });
  return response.data;
};

export const fetchChatConversations = async ({ page = 0, size = 20 } = {}) => {
  const isUuidLike = (value) =>
    /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
      String(value || "").trim()
    );

  const isAutoGeneratedThreadTitle = (value) => {
    const normalized = String(value || "").trim();
    if (!normalized) return true;
    const lowered = normalized.toLowerCase();
    if (isUuidLike(normalized)) return true;
    if (lowered.startsWith("chat ")) {
      const suffix = normalized.slice(5).trim();
      return isUuidLike(suffix);
    }
    return false;
  };

  const toMillis = (value) => {
    const time = value ? new Date(value).getTime() : 0;
    return Number.isFinite(time) ? time : 0;
  };

  const normalizeConversationList = (rawList) => {
    const map = new Map();
    (Array.isArray(rawList) ? rawList : []).forEach((item) => {
      const conversationId = item?.conversationId || item?.threadId;
      // ChatGPT-style history must be conversation/thread based only.
      // Ignore records without a stable conversation ID to avoid fake/duplicate rows.
      if (!conversationId) return;
      const updatedAt = item?.updatedAt || item?.createdAt || null;
      const incomingUpdatedAtMs = toMillis(updatedAt);
      const titleCandidate =
        item?.title ||
        item?.userMessage ||
        item?.lastMessagePreview ||
        "Untitled conversation";
      const previewCandidate =
        item?.lastMessagePreview ||
        item?.assistantResponse ||
        item?.userMessage ||
        "";
      const hasPreview = Boolean(String(previewCandidate || "").trim());
      const hasHumanTitle = !isAutoGeneratedThreadTitle(item?.title);
      // Suppress ghost/duplicate conversations that backend may emit
      // with only generated UUID title and no preview text.
      if (!hasPreview && !hasHumanTitle) return;

      if (!map.has(conversationId)) {
        map.set(conversationId, {
          conversationId,
          title: String(titleCandidate).slice(0, 140),
          lastMessagePreview: String(previewCandidate).slice(0, 240),
          language: item?.language || "en",
          source: item?.source || "LLM",
          createdAt: item?.createdAt || updatedAt,
          updatedAt,
        });
        return;
      }

      const existing = map.get(conversationId);
      const existingUpdatedAtMs = toMillis(existing?.updatedAt || existing?.createdAt);
      if (incomingUpdatedAtMs >= existingUpdatedAtMs) {
        map.set(conversationId, {
          ...existing,
          title: item?.title
            ? String(item.title).slice(0, 140)
            : existing.title,
          lastMessagePreview: String(previewCandidate).slice(0, 240),
          language: item?.language || existing.language,
          source: item?.source || existing.source,
          createdAt: existing.createdAt || item?.createdAt || updatedAt,
          updatedAt,
        });
      }
    });

    return Array.from(map.values()).sort(
      (a, b) =>
        toMillis(b?.updatedAt || b?.createdAt) -
        toMillis(a?.updatedAt || a?.createdAt)
    );
  };

  const normalizeConversationsPayload = (raw, fallbackPage = page, fallbackSize = size) => {
    const sourceList =
      raw?.history ||
      raw?.conversations ||
      raw?.items ||
      raw?.content ||
      [];
    const normalizedList = normalizeConversationList(sourceList);

    return {
      ...raw,
      history: normalizedList,
      page: Number.isFinite(raw?.page) ? raw.page : fallbackPage,
      size: Number.isFinite(raw?.size) ? raw.size : fallbackSize,
      hasMore:
        typeof raw?.hasMore === "boolean"
          ? raw.hasMore
          : Number.isFinite(raw?.totalPages) && Number.isFinite(raw?.page)
            ? raw.page + 1 < raw.totalPages
            : false,
    };
  };

  try {
    const response = await HISTORY_API.get("/chat/conversations", {
      params: { page, size },
      headers: getUserPhoneHeader(),
      withCredentials: true,
    });

    const normalized = normalizeConversationsPayload(response.data);
    if (normalized.history.length > 0 || page > 0) {
      return normalized;
    }
  } catch {
    // Fall through to /chat/history compatibility mode
  }

  // Compatibility mode: some backend deployments still expose data primarily through /chat/history.
  const historyResponse = await HISTORY_API.get("/chat/history", {
    params: { page, size },
    headers: getUserPhoneHeader(),
    withCredentials: true,
  });

  const historyData = historyResponse.data || {};
  const historyItems =
    historyData?.history || historyData?.items || historyData?.content || [];

  return normalizeConversationsPayload(
    {
      ...historyData,
      history: (Array.isArray(historyItems) ? historyItems : []).filter(
        (item) => item?.conversationId || item?.threadId
      ),
    },
    page,
    size
  );
};

export const fetchConversationMessages = async (
  conversationId,
  { page = 0, size = 50 } = {}
) => {
  const response = await HISTORY_API.get(
    `/chat/conversations/${conversationId}/messages`,
    {
      params: { page, size },
      headers: getUserPhoneHeader(),
      withCredentials: true,
    }
  );
  return response.data;
};

export const renameConversationTitle = async (conversationId, title) => {
  const response = await HISTORY_API.patch(
    `/chat/conversations/${conversationId}/title`,
    { title },
    {
      headers: getUserPhoneHeader(),
      withCredentials: true,
    }
  );
  return response.data;
};
